// Generated by gencpp from file vel_to_control/vel2control.msg
// DO NOT EDIT!


#ifndef VEL_TO_CONTROL_MESSAGE_VEL2CONTROL_H
#define VEL_TO_CONTROL_MESSAGE_VEL2CONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vel_to_control
{
template <class ContainerAllocator>
struct vel2control_
{
  typedef vel2control_<ContainerAllocator> Type;

  vel2control_()
    {
    }
  vel2control_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::vel_to_control::vel2control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vel_to_control::vel2control_<ContainerAllocator> const> ConstPtr;

}; // struct vel2control_

typedef ::vel_to_control::vel2control_<std::allocator<void> > vel2control;

typedef boost::shared_ptr< ::vel_to_control::vel2control > vel2controlPtr;
typedef boost::shared_ptr< ::vel_to_control::vel2control const> vel2controlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vel_to_control::vel2control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vel_to_control::vel2control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace vel_to_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vel_to_control::vel2control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vel_to_control::vel2control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vel_to_control::vel2control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vel_to_control::vel2control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vel_to_control::vel2control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vel_to_control::vel2control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vel_to_control::vel2control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::vel_to_control::vel2control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::vel_to_control::vel2control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vel_to_control/vel2control";
  }

  static const char* value(const ::vel_to_control::vel2control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vel_to_control::vel2control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::vel_to_control::vel2control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vel_to_control::vel2control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vel2control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vel_to_control::vel2control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::vel_to_control::vel2control_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // VEL_TO_CONTROL_MESSAGE_VEL2CONTROL_H
